name: HEMS CI/CD pepline 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
 
 build:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t nirminedh/homeenergymanagementsystemhems:v1.0.0 .
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push nirminedh/homeenergymanagementsystemhems:v1.0.0
 deploy:

  name : deploy 
  needs: build
  runs-on: ubuntu-latest
  steps :
    - uses: actions/checkout@master
    - name: Install Minikube and Kubectl
      run: |
          curl -LO "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker
          
    - name: Configure Docker credentials for Minikube
      run: |
         echo "$DOCKER_PASSWORD" | minikube ssh "echo $DOCKER_USERNAME > /tmp/docker-username && echo $DOCKER_PASSWORD > /tmp/docker-password && sudo mkdir -p /root/.docker && sudo mv /tmp/docker-username /root/.docker/config.json && sudo chmod 600 /root/.docker/config.json"

    - name: Pull Docker image from Docker Hub
      run: |
         
          docker pull nirminedh/homeenergymanagementsystemhems:v1.0.0
          
    - name: Deploy to Minikube
      run: |
          kubectl apply -f homeenergymanagementsystem-deployment.yaml
          kubectl apply -f homeenergymanagementsystem-service.yaml
    - name: Get pod names
      run: |
              PODS=$(kubectl get pods -l app=homeenergymanagementsystem -o jsonpath='{.items[*].metadata.name}')
               echo "Pods: $PODS"
    - name: Describe pods
      run: |
         PODS=$(kubectl get pods -l app=homeenergymanagementsystem -o jsonpath='{.items[*].metadata.name}')
         for POD in $PODS; do
         kubectl describe pod $POD
         done      
    - name: test url 
      run : |
       kubectl get pod
       kubectl get deployment 
      
