name: HEMS CI/CD pepline 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
 
 build:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t nirminedh/homeenergymanagementsystemhems:latest .
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push nirminedh/homeenergymanagementsystemhems:latest
 deploy:

  name : deploy 
  needs: build
  runs-on: ubuntu-latest
  steps :
    - uses: actions/checkout@master
    - name: Install Minikube and Kubectl
      run: |
          curl -LO "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start
          
    - name: build to minikube
      run: |
        eval $(minikube -p minikube docker-env) 
        docker build -t homeenergymanagementsystemhems:latest .
        docker image ls 
          
    - name: Deploy to Minikube
      run: |
          kubectl apply -f homeenergymanagementsystem-deployment.yaml
          kubectl apply -f homeenergymanagementsystem-service.yaml
    - name: Test service URLs
      run: |
                kubectl get deployment 
                kubectl get pods

      
